# This code is licensed from CircleCI to the user under the MIT license.
# See here for details: https://circleci.com/developer/orbs/licensing
version: 2.1

setup: yes

orbs:
  orb-tools: circleci/orb-tools@12.0.4
  hello: ./src/Hello-yml
  github: circleci/github-cli@2.2.0
commands:
    echo-command:
        description: echoコマンド
        parameters:
            to:
                default: World
                type: string
        steps:
            - run: echo "Hello, << parameters.to >>"
description: My First Orb
executors:
    default:
        docker:
            - image: busybox
jobs:
    echo-job:
        # This job will run commands from this code chunk
        description: echoジョブ
        executor: default
        parameters:
            to:
                default: World
                type: string
        steps:
            - echo-command:
                to: << parameters.to >>
    command-test:
        # This job will call "echo-command" from the "commands" section above
        executor: default
        steps:
            - echo-command:
                to: "ME!"
            - echo-command:
                to: "YOU!"
            - echo-command


workflows:
  build_and_test:
    jobs:
      - echo-job
      - command-test