version: 2.1
description: |
    Sample orb description
commands:
    echo-command:
        description: echoコマンド
        parameters:
            to:
                default: World
                type: string
        steps:
            - run: echo "Hello, << parameters.to >>"
executors:
    default:
        description: |
            This is a sample executor using Docker and Node. If you want to provide a custom environment in your orb, insert your image here. If you do not require an executor, you can simply delete this directory.
        docker:
            - image: cimg/node:<<parameters.tag>>
        parameters:
            tag:
                default: lts
                description: |
                    Pick a specific cimg/node image variant: https://hub.docker.com/r/cimg/node/tags
                type: string
jobs:
    command-test:
        description: |
            Sample description
        executor: default
        steps:
            - echo-command:
                to: ME!
            - echo-command:
                to: YOU!
examples:
    example:
        description: |
            Sample example description.
        usage:
            version: "2.1"
            orbs:
                <orb-name>: <namespace>/<orb-name>@1.2.3
            workflows:
                use-my-orb:
                    jobs:
                        - <orb-name>/<job-name>
# The "workflows section has to be manually added after doing a "circleci orb pack"
workflows:
    hello:
        jobs:
            - command-test
